- name: configure mariadb
  hosts: 127.0.0.1
  become: yes
  vars:
   root_pwd: '1rootPass#'
  connection: local
  tasks:
  - name: mysql_secure_installation Command Test
    expect:
      command: mysql_secure_installation
      responses:
        (.*)Enter current password for root(.*) : ''
        (.*)Set root password(.*): 'y'
        'New password:' : "{{root_pwd}}"
        'Re-enter new password:' : "{{root_pwd}}"
        (.*)Remove anonymous users(.*) : 'y'
        (.*)Disallow root login remotely(.*) : 'y'
        (.*)Remove test database and access to it(.*) : 'y'
        (.*)Reload privilege tables now(.*): 'y'
      echo: yes

  - name: configure-maria-artifactory
    expect:
      command: /opt/jfrog/artifactory/bin/configure.mysql.sh
      responses:
        (.*)Please enter the MySQL server admin username(.*) : ''
        (.*)Please enter the MySQL server admin password:(.*) : "{{root_pwd}}"
        (.*)Please enter the Artifactory database username(.*) : ''
        (.*)Please enter the Artifactory database password(.*) : ''
        (.*)Does the current server has access to the Internet(.*) : 'Y'
        (.*)Press enter to exit(.*) : ''
      echo: yes
